### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/pauromeubruguera-bootstrapFeed#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @pauromeubruguera ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Muy bien utilizadas las clases de bootstrap sin apoyarte en un `styles.css` :v:
- Elimina el style.css que no estás usando

**Comment by pauromeubruguera** [comment]
Ya esta!

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo... a por el siguiente!!!
